# Generated by Django 4.1.5 on 2023-01-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.IntegerField()),
                ("data", models.DateField()),
                ("valor", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=20)),
                ("hora", models.TimeField()),
                ("donoDaLoja", models.CharField(max_length=30)),
                ("nomeDaLoja", models.CharField(max_length=30)),
            ],
        ),
    ]
