# Generated by Django 4.1.5 on 2023-01-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularioCNAB", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="nomeDaLoja",
            new_name="nomeLoja",
        ),
    ]
