# Generated by Django 4.1.5 on 2023-01-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularioCNAB", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormCnab",
        ),
    ]
